---
title: "Seminar 1"
author: "Eric G. E. Nilsen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hei jeg heter Eric 


```{r}

#Her så skriver all koden vår
2+2
To <- 2
To + 2

#Her skriver som ikke kjøres


sett_med_tall <- c(2,4,5,2,4,44,4,4)
sett_med_tall
mean(sett_med_tall)
sum(sett_med_tall)
sd(sett_med_tall)
sett_med_tall





```

Denne regjresjonmodellen kan ikke stave regresjon 



```{r}


#install.packages("devtools")
#devtools::install_github("avehtari/ROS-Examples",subdir = "rpackage")
library(rosdata)
#install.packages("tidyverse")
library(tidyverse)
```





```{r}

View(earnings)
earnings <- earnings
mean(earnings$earn)
library(tidyverse)

earnings2 <- filter(earnings, smokenow == 2)

earnings %>%
  filter(smokenow == 2) %>% 
  select(weight, male, height) %>% 
  group_by(male) %>% 
  summarise(weight = mean(weight, na.rm = TRUE),
            height = mean(height, na.rm = TRUE))
  





```


```{r}
#Som dere ser kan jeg nå skrive 2 + To og få ut resultatet fire. Når vi nå skriver "To" vet R at vi
# *egentlig* mener tallet 2. For så enkle ting som dette er sikkert enklere å bare skrive 2, eller
#bare bruke en kalkulator for den saks skyld. Det fine med objekter er at de kan inneholde veldig mye
#informasjon! I første omgang kan vi prøve å lagre flere tall. Det er flere måter vi kan gjøre dette
#på, f.eks. kan vi skrive 1:10 for å få alle heltallene mellom 1 og 10, eller skrive c(1,22,5,2,1) for
#å lage en rekke tall. I det siste skiller jeg tallene med komma. Objektene kan hete hva du vil forøvrig. 
Hva_Du_Vil <- 1:100
Forovrig <- c(1,4,56,8,4,2,4)
#Eneste er at du ikke kan ha mellomrom i navnene eller tall som første tegn, og det er god kutyme å unnå
#æ/ø/å generelt i script.
#Nå som vi har et script med flere elementer kan vi prøve å kjøre noen funksjoner på dem
#Det kan nevnes at funksjoner faktisk er objekter de og, men det blir først innteresant når du holder
#på med litt mer avansert kode. La oss se om vi kan finne gjennomsnittet av disse vektorene. 
mean(Forovrig)
```

