---
title: "Seminar 1_4"
author: "Eric G. E. Nilsen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Her kan jeg skrive kode

```{r}


# install.packages("devtools")
#devtools::install_github("avehtari/ROS-Examples",subdir = "rpackage", force = TRUE)
# Kommentar
# install.packages("tidyverse")
library("tidyverse")

```

```{r, eval=FALSE}

To <- 2
To + 2

flere_tall <- c(2,44,4,4,2,3,4,3,12)
flere_tall[3]
mean(flere_tall)
sum(flere_tall)
?mean

NA
missing_data <- c(2,4,NA,2,3)
mean(missing_data, na.rm = TRUE)

library(rosdata)
library(tidyverse)

earnings <- earnings

mean(earnings$ethnicity)
class(earnings$ethnicity)

mean(earnings$age)



```

## Tidyverse

```{r, eval=FALSE}
#<- 
 (2 == 2) & (2 > 8)
earnings %>% 
  filter(age < 20 & smokenow == 2) %>% 
  mutate(exercise_often = ifelse(exercise > 5, 1, 0)) %>% 
  ggplot(aes(walk, earn)) +
    geom_point() +
  theme_classic()



```
