---
title: "Seminar13"
author: "Eric G. E. Nilsen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Her kan jeg skrive det jeg vil av tekst

```{r, eval=FALSE}


2+2

To <- 2

To + 2

flere_Tall <- c(3,4,2,1,3,42,3)
class(flere_Tall)
mean(flere_Tall)
sum(flere_Tall)
sd(flere_Tall)
tekst <- c("Dett", "er en ", "  tekst")

mean(tekst)

library(tidyverse)
library(rosdata)

earnings <- earnings

mean(earnings$age)

earnings %>%
  filter(smokenow == 2) %>%
  select(male, earn, exercise) %>% 
  mutate( exersice_much = ifelse(exercise > 3, 1, 0)) %>% 
  group_by(male) %>% 
  summarise(earn = mean(earn)) %>% 
  ggplot(aes(male, earn, fill = factor(male))) +
  geom_col() +
  theme_classic()
  
earnings %>% 
  filter(smokenow == 2) %>% 
  ggplot(aes(earn, fill = factor(male))) +
  geom_density()

earnings %>%
  #filter(smokenow == 2) %>%
  select(male, earn, exercise, smokenow) %>% 
  mutate( exersice_much = ifelse(exercise > 3, 1, 0)) %>% 
  group_by(male) %>% 
  mutate(earn = mean(earn)) %>% 
    ggplot(aes(male, earn, fill = factor(exersice_much))) +
  geom_col() +
  theme_classic()


ggplot(earnings, aes(height, log10(earn))) +
  geom_point(aes(colour = factor(male))) +
  geom_smooth(method = "lm") +
  ggthemes::theme_excel_new() 

```



